pipeline {
    agent { label 'mac-qa' }

    options {
        ansiColor('xterm')
    }

    tools {
        nodejs 'latest'
        jdk 'latest'
    }
    stages {
        stage('Install packages') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run tests -- chrome') {
            steps {
              sh 'npx cypress run --browser chrome --spec cypress/specs/ui/**.cy.js'
            }
        }
        stage('Run tests -- api') {
            steps {
              sh 'npx cypress run --spec cypress/specs/api/**.cy.js'
            }
        }
    }
}
