pipeline {
    agent { label 'mac-qa' }

    tools {
        nodejs 'latest'
        jdk 'latest'
    }
    stages {
        stage('Install packages') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run tests') {
            steps {
              sh 'npx cypress run'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'video/'
        }
    }
}
