name: Run Automation
on:
  push:
    branches:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install -g eslint
      - run: eslint . --ext .js,.jsx,.ts,.tsx

  run-cypress:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
          npm install
      - uses: cypress-io/github-action@v6
